# Generated by Django 3.2.9 on 2022-01-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20220129_1028'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='order_line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.orderlineitem'),
        ),
    ]
