# Generated by Django 3.2.9 on 2022-02-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220131_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_line',
        ),
    ]
