# Generated by Django 3.2.9 on 2022-02-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
